import { useState, useEffect } from 'react';
import { useAuth } from '../context/AuthContext';
import {
  FileText,
  Download,
  Plus,
  Loader2,
  Calendar,
  Clock,
  AlertTriangle,
  CheckCircle,
} from 'lucide-react';
import api from '../api';

export default function ReportsPage() {
  const { isAdmin } = useAuth();
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [message, setMessage] = useState(null);

  useEffect(() => {
    fetchReports();
  }, []);

  const fetchReports = async () => {
    try {
      const { data } = await api.get('/reports');
      setReports(data);
    } catch (err) {
      console.error('Failed to fetch reports:', err);
    } finally {
      setLoading(false);
    }
  };

  const handleGenerate = async () => {
    setGenerating(true);
    setMessage(null);
    try {
      const { data } = await api.post('/generate-pdf-now');
      setMessage({
        type: 'success',
        text: `Report generated: ${data.filename}`,
      });
      fetchReports();
    } catch (err) {
      setMessage({
        type: 'error',
        text: err.response?.data?.detail || 'Failed to generate report',
      });
    } finally {
      setGenerating(false);
      setTimeout(() => setMessage(null), 5000);
    }
  };

  const handleDownload = (reportId, filename) => {
    const token = localStorage.getItem('token');
    fetch(`/api/reports/${reportId}/download`, {
      headers: { Authorization: 'Bearer ' + token },
    })
      .then((res) => {
        if (!res.ok) throw new Error('Download failed');
        return res.blob();
      })
      .then((blob) => {
        const url = window.URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = filename;
        document.body.appendChild(a);
        a.click();
        a.remove();
        window.URL.revokeObjectURL(url);
      })
      .catch((err) => {
        console.error('Download error:', err);
        setMessage({ type: 'error', text: 'Failed to download report' });
        setTimeout(() => setMessage(null), 4000);
      });
  };

  const formatDate = (dateStr) => {
    const d = new Date(dateStr);
    return d.toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
    });
  };

  const formatTime = (dateStr) => {
    const d = new Date(dateStr);
    return d.toLocaleTimeString('en-US', {
      hour: '2-digit',
      minute: '2-digit',
      hour12: false,
    });
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <FileText size={22} className="text-noc-accent" />
          <h1 className="text-xl font-bold">PDF Reports</h1>
        </div>
        {isAdmin && (
          <button
            onClick={handleGenerate}
            disabled={generating}
            className="btn-primary flex items-center gap-2"
          >
            {generating ? (
              <Loader2 size={16} className="animate-spin" />
            ) : (
              <Plus size={16} />
            )}
            {generating ? 'Generating...' : 'Generate Now'}
          </button>
        )}
      </div>

      {/* Status message */}
      {message && (
        <div
          className={`flex items-center gap-2 text-sm rounded-lg p-3 border
          ${
            message.type === 'success'
              ? 'bg-noc-green/10 border-noc-green/20 text-noc-green'
              : 'bg-noc-red/10 border-noc-red/20 text-noc-red'
          }`}
        >
          {message.type === 'success' ? (
            <CheckCircle size={16} />
          ) : (
            <AlertTriangle size={16} />
          )}
          {message.text}
        </div>
      )}

      {/* Reports table */}
      {loading ? (
        <div className="card flex items-center justify-center py-12 text-noc-dim">
          <Loader2 size={20} className="animate-spin mr-2" />
          Loading reports...
        </div>
      ) : reports.length === 0 ? (
        <div className="card flex flex-col items-center justify-center py-16 text-noc-dim">
          <FileText size={40} className="mb-3 opacity-30" />
          <p className="text-lg">No reports generated yet</p>
          <p className="text-sm mt-1">
            {isAdmin
              ? 'Click "Generate Now" to create your first report'
              : 'Reports will appear here once generated by an admin'}
          </p>
        </div>
      ) : (
        <div className="card overflow-hidden p-0">
          <table className="w-full">
            <thead>
              <tr className="border-b border-noc-border">
                <th className="text-left text-xs font-medium text-noc-muted px-4 py-3">
                  #
                </th>
                <th className="text-left text-xs font-medium text-noc-muted px-4 py-3">
                  Filename
                </th>
                <th className="text-left text-xs font-medium text-noc-muted px-4 py-3">
                  Generated
                </th>
                <th className="text-right text-xs font-medium text-noc-muted px-4 py-3">
                  Action
                </th>
              </tr>
            </thead>
            <tbody>
              {reports.map((report, idx) => (
                <tr
                  key={report.id}
                  className="border-b border-noc-border/50 last:border-0 hover:bg-noc-card/50 transition-colors"
                >
                  <td className="px-4 py-3 text-sm text-noc-dim font-mono">
                    {reports.length - idx}
                  </td>
                  <td className="px-4 py-3">
                    <div className="flex items-center gap-2">
                      <FileText size={14} className="text-noc-accent" />
                      <span className="text-sm font-medium truncate max-w-xs">
                        {report.filename}
                      </span>
                    </div>
                  </td>
                  <td className="px-4 py-3">
                    <div className="flex items-center gap-3 text-sm text-noc-muted">
                      <span className="flex items-center gap-1">
                        <Calendar size={12} />
                        {formatDate(report.generated_at)}
                      </span>
                      <span className="flex items-center gap-1">
                        <Clock size={12} />
                        {formatTime(report.generated_at)}
                      </span>
                    </div>
                  </td>
                  <td className="px-4 py-3 text-right">
                    <button
                      onClick={() =>
                        handleDownload(report.id, report.filename)
                      }
                      className="btn-ghost inline-flex items-center gap-1.5 text-sm py-1.5 px-3"
                    >
                      <Download size={14} />
                      Download
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}
